# Generated by Django 3.2.6 on 2021-08-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210810_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('_type', models.CharField(blank=True, max_length=100, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='Prjoects/')),
            ],
        ),
    ]
