# Generated by Django 3.2.6 on 2021-10-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210813_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to='Prjoects/'),
        ),
    ]
