# Generated by Django 3.2.6 on 2021-10-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.CharField(blank=True, max_length=5048, null=True),
        ),
    ]
